name: Build Android App
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Europe/Kiev
    steps:
      - uses: actions/checkout@v4
      - name: Set timezone for build
        run: sudo timedatectl set-timezone Europe/Kiev
      - name: Initialize project
        run: bash .github/workflows/init-android.sh
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew assemble${{ env.BUILD_TYPE || 'debug' }}
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-${{ env.BUILD_TYPE || 'debug' }}-apk
          path: app/build/outputs/apk/${{ env.BUILD_TYPE || 'debug' }}/*.apk